name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: CI
        run: |
          xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
